services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - type: bind
        source: ./uploads
        target: /app/uploads
        bind:
          create_host_path: true
      - type: bind
        source: ./output
        target: /app/output
        bind:
          create_host_path: true
      - type: bind
        source: ./logs
        target: /app/logs
        bind:
          create_host_path: true
    environment:
      - FLASK_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
